formatter: markdown table
output_file: README.md
output_mode: inject
sort_by: false

sections:
  modules:
    show: true

settings:
  anchor: true
  collapse_nested_modules: false
  default: true
  description: true
  escape: true
  hide_empty: false
  html: true
  indent: 2
  lockfile: true
  read_comments: true
  required: true
  sensitive: true
  show_check: false
  type: true
